---
- name: Render traefik config
  template:
    src: traefik.toml.j2
    dest: "{{ traefik_directory }}/traefik.toml"
  notify: restart traefik

- name: Render docker-compose config
  template:
    src: docker-compose.yml.j2
    dest: "{{ traefik_directory }}/docker-compose.yml"
  notify: start traefik

- name: Check that acme.json exists
  stat:
    path: "{{ traefik_directory }}/acme.json"
  when: traefik_acme_enable
  register: acme

- name: Ensure acme config
  file:
    path: "{{ traefik_directory }}/acme.json"
    state: touch
    mode: 0600
  when: acme.stat.exists == False

- name: Create traefik external network
  docker_network:
    name: "{{ traefik_docker_external_network }}"
    state: present

- name: Create traefik internal network
  docker_network:
    name: "{{ traefik_docker_internal_network }}"
    state: present

- name: Pull Docker image
  docker_image:
    name: traefik
    source: pull
    tag: "{{ traefik_version }}"
  notify: start traefik
