---
- include: install.yml

- include: configure.yml

- name: inspect traefik
  docker_container_info:
    name: traefik
  register: traefik_container_details0
  # want to remove the task from the playbook.
  # when: 0 > 1

- name: get traefik IP address
  set_fact:
    traefik_ip_address: "{{ traefik_container_details | json_query(jmesquery) }}"
  vars:
    jmesquery: "container.NetworkSettings.Networks.{{ traefik_docker_external_network }}.IPAddress"
  # want to remove the task from the playbook.
  # when: 0 > 1

- name: inspect oidc client
  docker_container_info:
    name: oidc
  register: oidc_container_details
  # want to remove the task from the playbook.
  # when: 0 > 1

- name: get oidc IP address
  set_fact:
    oidc_ip_address: "{{ oidc_container_details | json_query(jmesquery) }}"
  vars:
    jmesquery: "container.NetworkSettings.Networks.{{ traefik_docker_internal_network }}.IPAddress"
  # want to remove the task from the playbook.
  # when: 0 > 1
