---
# Install
vault_version: "1.13.3"
vault_directory: "/opt/vault"
vault_master_secrets: "/root/vault-master-secrets"

# General settings
vault_port: 8200
vault_log_level: "ERROR"
vault_accesslog_enable: false
vault_shares: 5
vault_treshold: 3
vault_clean_data: false

# Vault Config settings
vault_ui: "true"
vault_max_lease_ttl: "2160h"
vault_default_lease_ttl: "2160h"
vault_tls_disable: "true"
vault_disable_clustering: "true"

# Docker
vault_docker_enable: true
vault_docker_expose_by_default: false
