---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ vault_directory }}"
    - "{{ vault_directory }}/etc"

- name: Create vault secrets directory
  file:
    path: "{{ vault_master_secrets }}"
    state: "directory"
    mode: "0600"
