---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ rclone_directory }}"

- name: Git checkout
  ansible.builtin.git:
    repo: "https://github.com/HarryKodden/encrypted-mounting.git"
    dest: "{{ rclone_directory }}"
    update: yes
    force: yes

- name: Git checkout SRAM Token Service
  ansible.builtin.git:
    repo: "https://github.com/HarryKodden/SRAM-Token-Service.git"
    dest: "{{ rclone_directory }}/tmp-pam"
    update: yes
    force: yes

- name: Copy SRAM Token PAM module...
  shell: "cp {{ rclone_directory }}/tmp-pam/bin/sram-token.py {{ rclone_directory }}/mount/pam-validate.py"

- name: Remove SRAM Token Service
  file:
    state: absent
    path: "{{ rclone_directory }}/tmp-pam"

- name: Render env file
  template:
    src: rclone-env.j2
    dest: "/root/rclone-env"
    mode: 0600

- name: Render docker-compose config
  template:
    src: docker-compose.yml.j2
    dest: "{{ rclone_directory }}/docker-compose.yml"

- name: Render oidc.conf for nginx
  template:
    src: oidc.conf.j2
    dest: "{{ rclone_directory }}/oidc.conf"

- name: copy mount.conf
  copy:
    src: files/mount.conf
    dest: "{{ rclone_directory }}/mount.conf"

- name: copy index.php
  copy:
    src: files/index.php
    dest: "{{ rclone_directory }}/index.php"

- name: Stop rclone
  docker_compose:
    project_src: "{{ rclone_directory }}"
    state: absent
    remove_volumes: yes

- name: Start rclone
  docker_compose:
    project_src: "{{ rclone_directory }}"
    state: present
    build: yes
